### ISSUE TITLE
feat: GitHub ActionsでCI/CDパイプラインを設定する

### ISSUE THREAD

**Issue by ishiooon** [ishiooon/dotfiles#5]
## 概要
現在、dotfilesリポジトリにはGitHub Actionsによる自動テストやlintのワークフローが設定されていません。品質保証とメンテナンス性向上のため、CI/CDパイプラインの設定が必要です。

## 現状の問題点
- プルリクエスト時の自動チェックがない
- シェルスクリプトの構文エラーが事前に検出できない
- コードスタイルの一貫性が保証されない
- インストールスクリプトの動作確認が手動

### 1. 基本的なワークフロー構成
```yaml
# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
          
  test-install:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Test installation script
        run: |
          bash .bin/install.sh --dry-run
```

#### Linting
- [ ] ShellCheck: bashとzshスクリプトの静的解析
- [ ] Markdownlint: README.mdやドキュメントの書式チェック
- [ ] yamllint: 設定ファイルの構文チェック

#### Testing
- [ ] インストールスクリプトのドライラン
- [ ] シンボリックリンク作成の検証
- [ ] 各シェル関数の単体テスト（bats使用）

#### Security
- [ ] シークレットスキャン
- [ ] 依存関係の脆弱性チェック

#### Release automation
```yaml
# .github/workflows/release.yml
name: Release
on:
  push:
    tags:
      - 'v*'
```

#### Documentation
- [ ] 自動的にCHANGELOG.mdを更新
- [ ] インストール手順の自動テスト結果をREADMEに反映

## 期待される効果

1. **品質向上**: 構文エラーやバグの早期発見
2. **開発効率化**: PRレビュー前に問題を自動検出
3. **信頼性向上**: 複数OS環境での動作保証
4. **貢献しやすさ**: 新規コントリビューターも安心して貢献可能

## 実装の優先順位

1. ShellCheckによる静的解析（最優先）
2. インストールスクリプトのテスト
3. マルチOS対応テスト
4. セキュリティチェック

## 参考リンク
- [GitHub Actions documentation](https://docs.github.com/en/actions)
- [ShellCheck GitHub Action](https://github.com/ludeeus/action-shellcheck)
- [Bats-core (Bash Automated Testing System)](https://github.com/bats-core/bats-core)
